### ISSUE TITLE
Is there something need to send http request?

### ISSUE THREAD

**Issue by WLBRich** [liuyoude/STgram-MFN#6]
> `Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa56479e910>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/STgram_MFN_ArcFace(m=0.7,s=30) (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa56479e910>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/visdom/__init__.py", line 708, in _send
    return self._handle_post(
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/workspace/private/user-dataset-245759/envs/research/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/STgram_MFN_ArcFace(m=0.7,s=30) (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa56479e910>: Failed to establish a new connection: [Errno 111] Connection refused'))`
As you can see above，is there something need to send http request? I get something wrong about this.

**Comment by liuyoude** [comment]
This seems to be caused by visdom visualization. You need run "python -m visdom.server" firstly. I will update this in README, thank you!
